version: "3.1"
services:
  architects_hub_database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: architect_admin
      MYSQL_DATABASE: architect_hub
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 2s
      retries: 20
